backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: /images
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog Posts
    label_singular: Blog Post
    folder: src/blog-posts
    create: true
    preview_path: 'blog/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: documentation
    label: Documentation Pages
    label_singular: Documentation Page
    folder: src/documentation-pages
    create: true
    preview_path: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Sidenav', name: 'sidenav', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
